# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-05 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
